apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidecar-service
  labels:
    app: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sidecar-service
  template:
    metadata:
      labels:
        app: sidecar-service
    spec:
      containers:
        - name: invoice
          image: arthurws/invoice
          imagePullPolicy: Always
          ports:
            - containerPort: 3002

        - name: sidecar
          image: arthurws/sidecar
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: TARGET
              value: "http://localhost:3002"
---
kind: Service
apiVersion: v1
metadata:
  name: sidecar-service
spec:
  selector:
    app: sidecar-service
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer